### ISSUE TITLE
Music NFT Release Event

### ISSUE THREAD

**Issue by TimDaub** [neume-network/neuIPs#4]
- NeuIP-3 is in DRAFT: https://github.com/neume-network/neuIPs/blob/main/neuIPs/neuIP-3.md

**Comment by neatonk** [comment]
I think this could include album semantics as well. In which case a release would be either a single song or a collection of songs.

**Comment by TimDaub** [comment]
thinking a bit more about this: We could first define the standard within neuip and that guarantees that we're going to implement a strategy that crawls this. And then once we're very confident that it's useful, we'll propose as an EIP too. OK? /cc @djfnd

**Comment by neatonk** [comment]
Happy to help here too. I imagine the next step would be to discuss what this looks like in more detail?

**Comment by TimDaub** [comment]
Hey, happy you want to help! We need it!

So I think the criteria for being successful in doing this task is such that those in the music NFT industry who manage the events switch over.

A strategy here is to immitate and improve what already exists by making it mode widely available through a canonical specification.

Currently, I see two ways artifacts are emitted:

- zora, mintsongs, catalog: They all have one big contract that everyone mints their music in.
- sound, decent, noizd, manifold: They deploy an NFT on a per artist basis.

Now, right of the bat, for neume, what zora et al is doing is so much better. But what is the merit of e.g. sound's strategy? How to canonicalize? How would you approach this?

**Comment by neatonk** [comment]
For me this issue is all about semantics and I'd like to re-frame it a bit by way of an analogy to HTML. Take the humble `<div>`—for a time it was the best tool we had to structure content on the web, resulting in a div soup with a side of CSS class name's for styling. Unfortunately, neither the div nor the class names were capable of conveying the meaning of each element in a machine readable way. 

In our case, the ERC721 spec is like the `<div>` and each platforms is like a CSS class name. We use ERC721's to represent many different things and rely on our knowledge of the associated platform to apply the correct semantic meaning. To make this machine-readable way to apply semantic meaning to an NFT contract and it's tokens. 

This could be done with new contract events—as was already suggested—but it could also be done with new contract functions or additional metadata. One advantage of relying on additional metadata is that it could be applied to existing NFTs, by whoever controls the `tokenURI`.

**Comment by neatonk** [comment]
This Serenade Digital Pressing standard described in the article below uses an additional metadata file to accomplish something like this: https://mirror.xyz/serenademusic.eth/nB2Wu7MOFP29B6MbvPXWfJTNCh31Wv30OLh6YGE40lk

**Comment by TimDaub** [comment]
This problem has resurfaced again in /strategies and I think we should really get this going: https://github.com/neume-network/strategies/issues/314

**Comment by neatonk** [comment]
Excited to see this moving forward @TimDaub. Thanks for putting this spec together and bringing attention to it.

I have two comments for discussion:
1. I think this spec would be more useful if the metadata requirements aligned more closely with existing music NFTs rather than neume's own schema.
2. Ideally, this spec (and neume) would support un-minted editions. This could be saved for a later revision, but is worth discussing now since editions have become so popular.

**Comment by TimDaub** [comment]
OK which schema are you thinking about?

**Comment by neatonk** [comment]
No particular spec, but rather a Frankenstein of commonly used specs and fields. Will have to do a little digging tomorrow to describe this with any precision.

**Comment by neatonk** [comment]
I can make a PR for review.

**Comment by neatonk** [comment]
Here it is... https://github.com/neume-network/neuIPs/pull/10

**Comment by royosherove** [comment]
How about an even more robust approach: 

Create an open contract called Neume Registry with but one function, and anyone who wants to be indexed will call this function. That way, you can index that as the single events source and put it on the graph, for example. 

This allows more of a "pull" model in which anyone can easily integrate without you acting as the gateway for indexing and creating a listener.

As a dev, I would be happy to contribute to that.

**Comment by TimDaub** [comment]
Thanks for your input!

> Create an open contract called Neume Registry with but one function, and anyone who wants to be indexed will call this function. That way, you can index that as the single events source and put it on the graph, for example.

The reason we're standardizing around an event is such that we can experiment with the robustness of the curation mechanism. E.g. the first versions of contracts that will emit the event may be puny and will allow bad actors to also submit events (which will end up being false). And over time, we want to make it more and more difficult/costly/risky for bad actors to emit the event with malicious intent.



> This allows more of a "pull" model in which anyone can easily integrate without you acting as the gateway for indexing and creating a listener.

I don't think, at this point, we're acting as a gateway. Technically today, anyone can also index this NewSong event with e.g., the Graph Protocol. And then additionally, for now, it seems optional whether this event is emitted specifically from a curation protocol contract or if artists emit it within their EIP-721 token contracts.

**Comment by TimDaub** [comment]
> Although a song may be represented by many tokens the event NewSong must only be emitted once on the network and preferrably with its lowest findable uint256 tokenId.

This line is problematic and instead what would be more useful is if we could e.g. allow a set of tokens to be connected to e.g. a song. Sometimes we have editions being minted for a song, so specifying a range would be useful (1-10), but sometimes it could be that it has to be a list if tokenIds (1, 4, 7).

**Comment by neatonk** [comment]
> This line is problematic and instead what would be more useful is if we could e.g. allow a set of tokens to be connected to e.g. a song.

Thanks for this. I agree and also had issues with the wording of that line. 

> Sometimes we have editions being minted for a song, so specifying a range would be useful (1-10), but sometimes it could be that it has to be a list if tokenIds (1, 4, 7).

Some additional points to consider:
- In the case of an open edition, it would be useful to have a way of specifying all `tokenId`s. This could be done as a range from 0 to the max uint256 value, but there is probably a better way.
- For any edition, you may end up with a token range including `tokenId`s that have not been minted yet. I'm thinking this is fine, but wanted to clarify.

**Comment by neatonk** [comment]
Some other thoughts spurred by the "open hours" conversation today...
- I think it makes sense to include the artist address as an indexed log argument. E.g.
  ```solidity
  event NewSong(
    address indexed artist, 
    address indexed contract, 
    uint256 indexed tokenId
  )
  ```
- Another way to get the details needed to make sense of a new song is to have them included in the event via a non-indexed argument. E.g. 
  ```solidity
  struct Song {
    string artist;
    string title;
    ...
  }
  event NewSong(
    address indexed artist, 
    address indexed contract, 
    uint256 indexed tokenId, 
    Song song
  )
  ```
- Interesting to note that one could drop the NFT part altogether if all of the information is provided in the event. E.g.
  ```solidity
  struct Song {
    string artist;
    string title;
    string description;
    string imageUri;
    string audioUri;
  }
  ```

**Comment by TimDaub** [comment]
I think now we‘re just getting started, right?
But what are people‘s opinion regarding on-chain storage as with a struct of variable length strings, this has now become a quite costly operation. A bytes32 content id could end up being a nice fit here too. But them again having all data available for as long as the token is around would arguably be useful. Is storing those strings a necessary cost to keep useful metadata around?
